### ISSUE TITLE
Generation dialog does not open: null at org.oddgen.sqldev.GenerateDialog.addParam(GenerateDialog.java:329)

### ISSUE THREAD

**Issue by ogobrecht** [oddgen/oddgen#54]
Hi Philipp,

I am currently working on a new version of our table API generator. After adding some new parameters the generation dialog on a table does not open. Instead I get an error on the logging page: 

- Source: oracle.dbtools.raptor.backgroundTask.RaptorTaskManager$1
- Message: null at org.oddgen.sqldev.GenerateDialog.addParam(GenerateDialog.java:329)

![image](https://user-images.githubusercontent.com/10425445/80317296-49a43880-8803-11ea-97d6-2ef7dd534ca7.png)

As you can see in the screenshot above the direct generation into a worksheet is working.

- Used oddgen version: 0.3.1
- Used SQL Developer version: 19.4 (Windows 10)

Resetting the session and/or restarting the SQL Developer does not help. Any ideas?

If you want to dive into the problem please check out our current [development branch](https://github.com/OraMUC/table-api-generator/tree/development) and run the single script `om_tapigen_install.sql` in the root folder to install the table API generator and also the oddgen wrapper.

Thank you for your help and best regards from Munich
Ottmar

**Comment by PhilippSalvisberg** [comment]
Hi Ottmar, 

Thank you for reporting this bug. We should catch this error and provide an appropriate error message so you can fix the generator (or we should fix the conflicting settings on the fly and show the dialog anyway).

In your case the valid values in the `get_lov` function of the `om_tapigen_oddgen_wrapper` package do not match the values you've set in `get_params` as default values.

Here are the default values (boolean values in upper case):

```
  FUNCTION get_params RETURN t_param IS
    v_params t_param;
  BEGIN
    v_params(c_parameter_descriptions) := 'https://github.com/OraMUC/table-api-generator/blob/master/docs/parameters.md';
    v_params(c_enable_insertion_of_rows) := 'TRUE';
    v_params(c_enable_column_defaults) := 'FALSE';
    v_params(c_enable_update_of_rows) := 'TRUE';
    v_params(c_enable_deletion_of_rows) := 'FALSE';
    v_params(c_enable_parameter_prefixes) := 'TRUE';
    v_params(c_enable_proc_with_out_params) := 'TRUE';
    v_params(c_enable_getter_and_setter) := 'TRUE';
    v_params(c_col_prefix_in_method_names) := 'TRUE';
    v_params(c_return_row_instead_of_pk) := 'FALSE';
    v_params(c_default_bulk_limit) := '1000';
    v_params(c_enable_dml_view) := 'FALSE';
    v_params(c_api_name) := NULL;
    v_params(c_sequence_name) := NULL;
    v_params(c_exclude_column_list) := NULL;
    v_params(c_audit_column_mappings) := NULL;
    v_params(c_audit_user_expression) := om_tapigen.c_audit_user_expression;
    v_params(c_row_version_column_mapping) := NULL;
    v_params(c_enable_custom_defaults) := 'FALSE';
    v_params(c_custom_default_values) := NULL;
    RETURN v_params;
  END get_params;
```

And here are the valid values (boolean values in lower case):

```
  FUNCTION get_lov RETURN t_lov IS
    v_lov t_lov;
  BEGIN
    v_lov(c_enable_insertion_of_rows) := NEW t_string('true', 'false');
    v_lov(c_enable_column_defaults) := NEW t_string('true', 'false');
    v_lov(c_enable_update_of_rows) := NEW t_string('true', 'false');
    v_lov(c_enable_deletion_of_rows) := NEW t_string('true', 'false');
    v_lov(c_enable_parameter_prefixes) := NEW t_string('true', 'false');
    v_lov(c_enable_proc_with_out_params) := NEW t_string('true', 'false');
    v_lov(c_enable_getter_and_setter) := NEW t_string('true', 'false');
    v_lov(c_col_prefix_in_method_names) := NEW t_string('true', 'false');
    v_lov(c_return_row_instead_of_pk) := NEW t_string('true', 'false');
    v_lov(c_enable_dml_view) := NEW t_string('true', 'false');
    v_lov(c_enable_custom_defaults) := NEW t_string('true', 'false');
    RETURN v_lov;
  END get_lov;
```

Adapt them and the dialog will be displayed. 

HTH
Philipp

**Comment by ogobrecht** [comment]
Hi Philipp,

Thank you very much for your quick response. And shame on me - I think it was late last night, and normally I should have seen that too. It's been several commits since I changed the boolean parameters from real booleans (constants from our tapigen package) to a direct string with a helper function around them. The helper function converted the booleans to a string in lower case, and I copied the default parameter values from our generator to upper case... as I mentioned earlier, it was late...  sorry...

Thanks for being kind enough to mark this as a bug and see a chance to improve your logic - the real problem was sitting in front of the computer, as it usually is...

Continue the good community work, it is very much appreciated.

Best regards
Ottmar

**Comment by PhilippSalvisberg** [comment]
Hi Ottmar,

No worries. I'm glad we found a solution. Nonetheless, I still think this is a bug in the oddgen extension. Just swallowing the error is not nice. 

Thanks,
Philipp
